// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	adminannouncements "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/announcements"
	adminauditlogs "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/auditlogs"
	admincoupons "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/coupons"
	admindashboard "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/dashboard"
	adminnodes "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/nodes"
	adminorders "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/orders"
	adminpaymentchannels "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/paymentchannels"
	adminPlanBillingOptions "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/planbillingoptions"
	adminplans "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/plans"
	adminprotocolbindings "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/protocolbindings"
	adminprotocolentries "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/protocolentries"
	adminsecurity "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/security"
	adminsite "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/site"
	adminsubscriptions "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/subscriptions"
	admintemplates "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/templates"
	adminusers "github.com/zero-net-panel/zero-net-panel/internal/handler/admin/users"
	auth "github.com/zero-net-panel/zero-net-panel/internal/handler/auth"
	shared "github.com/zero-net-panel/zero-net-panel/internal/handler/shared"
	useraccount "github.com/zero-net-panel/zero-net-panel/internal/handler/user/account"
	userannouncements "github.com/zero-net-panel/zero-net-panel/internal/handler/user/announcements"
	usernodes "github.com/zero-net-panel/zero-net-panel/internal/handler/user/nodes"
	userorders "github.com/zero-net-panel/zero-net-panel/internal/handler/user/orders"
	userpaymentchannels "github.com/zero-net-panel/zero-net-panel/internal/handler/user/paymentchannels"
	userplans "github.com/zero-net-panel/zero-net-panel/internal/handler/user/plans"
	usersubscriptions "github.com/zero-net-panel/zero-net-panel/internal/handler/user/subscriptions"
	"github.com/zero-net-panel/zero-net-panel/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// List announcements
				Method:  http.MethodGet,
				Path:    "/admin/announcements",
				Handler: adminannouncements.AdminListAnnouncementsHandler(serverCtx),
			},
			{
				// Create announcement
				Method:  http.MethodPost,
				Path:    "/admin/announcements",
				Handler: adminannouncements.AdminCreateAnnouncementHandler(serverCtx),
			},
			{
				// Publish announcement
				Method:  http.MethodPost,
				Path:    "/admin/announcements/:id/publish",
				Handler: adminannouncements.AdminPublishAnnouncementHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List audit logs
				Method:  http.MethodGet,
				Path:    "/admin/audit-logs",
				Handler: adminauditlogs.AdminAuditLogListHandler(serverCtx),
			},
			{
				// Export audit logs
				Method:  http.MethodGet,
				Path:    "/admin/audit-logs/export",
				Handler: adminauditlogs.AdminAuditLogExportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List coupons
				Method:  http.MethodGet,
				Path:    "/admin/coupons",
				Handler: admincoupons.AdminListCouponsHandler(serverCtx),
			},
			{
				// Create coupon
				Method:  http.MethodPost,
				Path:    "/admin/coupons",
				Handler: admincoupons.AdminCreateCouponHandler(serverCtx),
			},
			{
				// Update coupon
				Method:  http.MethodPatch,
				Path:    "/admin/coupons/:id",
				Handler: admincoupons.AdminUpdateCouponHandler(serverCtx),
			},
			{
				// Delete coupon
				Method:  http.MethodDelete,
				Path:    "/admin/coupons/:id",
				Handler: admincoupons.AdminDeleteCouponHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List admin console modules
				Method:  http.MethodGet,
				Path:    "/admin/dashboard",
				Handler: admindashboard.AdminDashboardHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List edge nodes
				Method:  http.MethodGet,
				Path:    "/admin/nodes",
				Handler: adminnodes.AdminListNodesHandler(serverCtx),
			},
			{
				// Create node
				Method:  http.MethodPost,
				Path:    "/admin/nodes",
				Handler: adminnodes.AdminCreateNodeHandler(serverCtx),
			},
			{
				// Update node
				Method:  http.MethodPatch,
				Path:    "/admin/nodes/:id",
				Handler: adminnodes.AdminUpdateNodeHandler(serverCtx),
			},
			{
				// Delete node
				Method:  http.MethodDelete,
				Path:    "/admin/nodes/:id",
				Handler: adminnodes.AdminDeleteNodeHandler(serverCtx),
			},
			{
				// Disable node
				Method:  http.MethodPost,
				Path:    "/admin/nodes/:id/disable",
				Handler: adminnodes.AdminDisableNodeHandler(serverCtx),
			},
			{
				// Get node kernel endpoints
				Method:  http.MethodGet,
				Path:    "/admin/nodes/:id/kernels",
				Handler: adminnodes.AdminNodeKernelsHandler(serverCtx),
			},
			{
				// Upsert node kernel endpoint
				Method:  http.MethodPost,
				Path:    "/admin/nodes/:id/kernels",
				Handler: adminnodes.AdminUpsertNodeKernelHandler(serverCtx),
			},
			{
				// Sync node kernel configuration
				Method:  http.MethodPost,
				Path:    "/admin/nodes/:id/kernels/sync",
				Handler: adminnodes.AdminSyncNodeKernelHandler(serverCtx),
			},
			{
				// Sync node status
				Method:  http.MethodPost,
				Path:    "/admin/nodes/status/sync",
				Handler: adminnodes.AdminSyncNodeStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List billing orders
				Method:  http.MethodGet,
				Path:    "/admin/orders",
				Handler: adminorders.AdminListOrdersHandler(serverCtx),
			},
			{
				// Get order detail
				Method:  http.MethodGet,
				Path:    "/admin/orders/:id",
				Handler: adminorders.AdminGetOrderHandler(serverCtx),
			},
			{
				// Cancel an order
				Method:  http.MethodPost,
				Path:    "/admin/orders/:id/cancel",
				Handler: adminorders.AdminCancelOrderHandler(serverCtx),
			},
			{
				// Manually mark an order as paid
				Method:  http.MethodPost,
				Path:    "/admin/orders/:id/pay",
				Handler: adminorders.AdminMarkOrderPaidHandler(serverCtx),
			},
			{
				// Refund an order
				Method:  http.MethodPost,
				Path:    "/admin/orders/:id/refund",
				Handler: adminorders.AdminRefundOrderHandler(serverCtx),
			},
			{
				// Process external payment callback
				Method:  http.MethodPost,
				Path:    "/admin/orders/payments/callback",
				Handler: adminorders.AdminPaymentCallbackHandler(serverCtx),
			},
			{
				// Reconcile an external payment
				Method:  http.MethodPost,
				Path:    "/admin/orders/payments/reconcile",
				Handler: adminorders.AdminReconcilePaymentHandler(serverCtx),
			},
			{
				// Process external payment callback without admin prefix
				Method:  http.MethodPost,
				Path:    "/payments/callback",
				Handler: adminorders.AdminPaymentCallbackPublicHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List payment channels
				Method:  http.MethodGet,
				Path:    "/admin/payment-channels",
				Handler: adminpaymentchannels.AdminListPaymentChannelsHandler(serverCtx),
			},
			{
				// Create payment channel
				Method:  http.MethodPost,
				Path:    "/admin/payment-channels",
				Handler: adminpaymentchannels.AdminCreatePaymentChannelHandler(serverCtx),
			},
			{
				// Get payment channel
				Method:  http.MethodGet,
				Path:    "/admin/payment-channels/:id",
				Handler: adminpaymentchannels.AdminGetPaymentChannelHandler(serverCtx),
			},
			{
				// Update payment channel
				Method:  http.MethodPatch,
				Path:    "/admin/payment-channels/:id",
				Handler: adminpaymentchannels.AdminUpdatePaymentChannelHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List plan billing options
				Method:  http.MethodGet,
				Path:    "/admin/plans/:plan_id/billing-options",
				Handler: adminPlanBillingOptions.AdminListPlanBillingOptionsHandler(serverCtx),
			},
			{
				// Create plan billing option
				Method:  http.MethodPost,
				Path:    "/admin/plans/:plan_id/billing-options",
				Handler: adminPlanBillingOptions.AdminCreatePlanBillingOptionHandler(serverCtx),
			},
			{
				// Update plan billing option
				Method:  http.MethodPatch,
				Path:    "/admin/plans/:plan_id/billing-options/:id",
				Handler: adminPlanBillingOptions.AdminUpdatePlanBillingOptionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List subscription plans
				Method:  http.MethodGet,
				Path:    "/admin/plans",
				Handler: adminplans.AdminListPlansHandler(serverCtx),
			},
			{
				// Create subscription plan
				Method:  http.MethodPost,
				Path:    "/admin/plans",
				Handler: adminplans.AdminCreatePlanHandler(serverCtx),
			},
			{
				// Update subscription plan
				Method:  http.MethodPatch,
				Path:    "/admin/plans/:id",
				Handler: adminplans.AdminUpdatePlanHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List protocol bindings
				Method:  http.MethodGet,
				Path:    "/admin/protocol-bindings",
				Handler: adminprotocolbindings.AdminListProtocolBindingsHandler(serverCtx),
			},
			{
				// Create protocol binding
				Method:  http.MethodPost,
				Path:    "/admin/protocol-bindings",
				Handler: adminprotocolbindings.AdminCreateProtocolBindingHandler(serverCtx),
			},
			{
				// Update protocol binding
				Method:  http.MethodPatch,
				Path:    "/admin/protocol-bindings/:id",
				Handler: adminprotocolbindings.AdminUpdateProtocolBindingHandler(serverCtx),
			},
			{
				// Delete protocol binding
				Method:  http.MethodDelete,
				Path:    "/admin/protocol-bindings/:id",
				Handler: adminprotocolbindings.AdminDeleteProtocolBindingHandler(serverCtx),
			},
			{
				// Sync protocol binding
				Method:  http.MethodPost,
				Path:    "/admin/protocol-bindings/:id/sync",
				Handler: adminprotocolbindings.AdminSyncProtocolBindingHandler(serverCtx),
			},
			{
				// Sync protocol bindings
				Method:  http.MethodPost,
				Path:    "/admin/protocol-bindings/sync",
				Handler: adminprotocolbindings.AdminSyncProtocolBindingsHandler(serverCtx),
			},
			{
				// Sync protocol binding status
				Method:  http.MethodPost,
				Path:    "/admin/protocol-bindings/status/sync",
				Handler: adminprotocolbindings.AdminSyncProtocolBindingStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List protocol entries
				Method:  http.MethodGet,
				Path:    "/admin/protocol-entries",
				Handler: adminprotocolentries.AdminListProtocolEntriesHandler(serverCtx),
			},
			{
				// Create protocol entry
				Method:  http.MethodPost,
				Path:    "/admin/protocol-entries",
				Handler: adminprotocolentries.AdminCreateProtocolEntryHandler(serverCtx),
			},
			{
				// Update protocol entry
				Method:  http.MethodPatch,
				Path:    "/admin/protocol-entries/:id",
				Handler: adminprotocolentries.AdminUpdateProtocolEntryHandler(serverCtx),
			},
			{
				// Delete protocol entry
				Method:  http.MethodDelete,
				Path:    "/admin/protocol-entries/:id",
				Handler: adminprotocolentries.AdminDeleteProtocolEntryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get third-party security settings
				Method:  http.MethodGet,
				Path:    "/admin/security-settings",
				Handler: adminsecurity.AdminGetSecuritySettingHandler(serverCtx),
			},
			{
				// Update third-party security settings
				Method:  http.MethodPatch,
				Path:    "/admin/security-settings",
				Handler: adminsecurity.AdminUpdateSecuritySettingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get site settings
				Method:  http.MethodGet,
				Path:    "/admin/site-settings",
				Handler: adminsite.AdminGetSiteSettingHandler(serverCtx),
			},
			{
				// Update site settings
				Method:  http.MethodPatch,
				Path:    "/admin/site-settings",
				Handler: adminsite.AdminUpdateSiteSettingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List subscriptions
				Method:  http.MethodGet,
				Path:    "/admin/subscriptions",
				Handler: adminsubscriptions.AdminListSubscriptionsHandler(serverCtx),
			},
			{
				// Create subscription
				Method:  http.MethodPost,
				Path:    "/admin/subscriptions",
				Handler: adminsubscriptions.AdminCreateSubscriptionHandler(serverCtx),
			},
			{
				// Get subscription detail
				Method:  http.MethodGet,
				Path:    "/admin/subscriptions/:id",
				Handler: adminsubscriptions.AdminGetSubscriptionHandler(serverCtx),
			},
			{
				// Update subscription
				Method:  http.MethodPatch,
				Path:    "/admin/subscriptions/:id",
				Handler: adminsubscriptions.AdminUpdateSubscriptionHandler(serverCtx),
			},
			{
				// Disable subscription
				Method:  http.MethodPost,
				Path:    "/admin/subscriptions/:id/disable",
				Handler: adminsubscriptions.AdminDisableSubscriptionHandler(serverCtx),
			},
			{
				// Extend subscription expiry
				Method:  http.MethodPost,
				Path:    "/admin/subscriptions/:id/extend",
				Handler: adminsubscriptions.AdminExtendSubscriptionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List subscription templates
				Method:  http.MethodGet,
				Path:    "/admin/subscription-templates",
				Handler: admintemplates.AdminListSubscriptionTemplatesHandler(serverCtx),
			},
			{
				// Create subscription template
				Method:  http.MethodPost,
				Path:    "/admin/subscription-templates",
				Handler: admintemplates.AdminCreateSubscriptionTemplateHandler(serverCtx),
			},
			{
				// Update subscription template
				Method:  http.MethodPatch,
				Path:    "/admin/subscription-templates/:id",
				Handler: admintemplates.AdminUpdateSubscriptionTemplateHandler(serverCtx),
			},
			{
				// List template publish history
				Method:  http.MethodGet,
				Path:    "/admin/subscription-templates/:id/history",
				Handler: admintemplates.AdminSubscriptionTemplateHistoryHandler(serverCtx),
			},
			{
				// Publish subscription template
				Method:  http.MethodPost,
				Path:    "/admin/subscription-templates/:id/publish",
				Handler: admintemplates.AdminPublishSubscriptionTemplateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List users with filters
				Method:  http.MethodGet,
				Path:    "/admin/users",
				Handler: adminusers.AdminListUsersHandler(serverCtx),
			},
			{
				// Create a new user
				Method:  http.MethodPost,
				Path:    "/admin/users",
				Handler: adminusers.AdminCreateUserHandler(serverCtx),
			},
			{
				// Rotate user credential
				Method:  http.MethodPost,
				Path:    "/admin/users/:id/credentials/rotate",
				Handler: adminusers.AdminRotateUserCredentialHandler(serverCtx),
			},
			{
				// Force user logout
				Method:  http.MethodPost,
				Path:    "/admin/users/:id/force-logout",
				Handler: adminusers.AdminForceLogoutHandler(serverCtx),
			},
			{
				// Reset user password
				Method:  http.MethodPost,
				Path:    "/admin/users/:id/reset-password",
				Handler: adminusers.AdminResetUserPasswordHandler(serverCtx),
			},
			{
				// Update user roles
				Method:  http.MethodPatch,
				Path:    "/admin/users/:id/roles",
				Handler: adminusers.AdminUpdateUserRolesHandler(serverCtx),
			},
			{
				// Update user status (active/disabled)
				Method:  http.MethodPatch,
				Path:    "/admin/users/:id/status",
				Handler: adminusers.AdminUpdateUserStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Request password reset code
				Method:  http.MethodPost,
				Path:    "/auth/forgot",
				Handler: auth.AuthForgotPasswordHandler(serverCtx),
			},
			{
				// Authenticate user and issue token
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.AuthLoginHandler(serverCtx),
			},
			{
				// Refresh access token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.AuthRefreshHandler(serverCtx),
			},
			{
				// Register new user account
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.AuthRegisterHandler(serverCtx),
			},
			{
				// Reset password using verification code
				Method:  http.MethodPost,
				Path:    "/auth/reset",
				Handler: auth.AuthResetPasswordHandler(serverCtx),
			},
			{
				// Verify user email with code
				Method:  http.MethodPost,
				Path:    "/auth/verify",
				Handler: auth.AuthVerifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Service health check
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: shared.PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get user balance
				Method:  http.MethodGet,
				Path:    "/user/account/balance",
				Handler: useraccount.UserBalanceHandler(serverCtx),
			},
			{
				// Rotate credential
				Method:  http.MethodPost,
				Path:    "/user/account/credentials/rotate",
				Handler: useraccount.UserRotateCredentialHandler(serverCtx),
			},
			{
				// Change email
				Method:  http.MethodPost,
				Path:    "/user/account/email",
				Handler: useraccount.UserChangeEmailHandler(serverCtx),
			},
			{
				// Send email change code
				Method:  http.MethodPost,
				Path:    "/user/account/email/code",
				Handler: useraccount.UserEmailChangeCodeHandler(serverCtx),
			},
			{
				// Change password
				Method:  http.MethodPost,
				Path:    "/user/account/password",
				Handler: useraccount.UserChangePasswordHandler(serverCtx),
			},
			{
				// Get user profile
				Method:  http.MethodGet,
				Path:    "/user/account/profile",
				Handler: useraccount.UserProfileHandler(serverCtx),
			},
			{
				// Update user profile
				Method:  http.MethodPatch,
				Path:    "/user/account/profile",
				Handler: useraccount.UserUpdateProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List active announcements
				Method:  http.MethodGet,
				Path:    "/user/announcements",
				Handler: userannouncements.UserListAnnouncementsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List node runtime status (sanitized)
				Method:  http.MethodGet,
				Path:    "/user/nodes",
				Handler: usernodes.UserListNodesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create order from plan
				Method:  http.MethodPost,
				Path:    "/user/orders",
				Handler: userorders.UserCreateOrderHandler(serverCtx),
			},
			{
				// List user orders
				Method:  http.MethodGet,
				Path:    "/user/orders",
				Handler: userorders.UserListOrdersHandler(serverCtx),
			},
			{
				// Get user order detail
				Method:  http.MethodGet,
				Path:    "/user/orders/:id",
				Handler: userorders.UserGetOrderHandler(serverCtx),
			},
			{
				// Cancel user order
				Method:  http.MethodPost,
				Path:    "/user/orders/:id/cancel",
				Handler: userorders.UserCancelOrderHandler(serverCtx),
			},
			{
				// Get user order payment status
				Method:  http.MethodGet,
				Path:    "/user/orders/:id/payment-status",
				Handler: userorders.UserGetOrderPaymentStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List payment channels
				Method:  http.MethodGet,
				Path:    "/user/payment-channels",
				Handler: userpaymentchannels.UserListPaymentChannelsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List available plans
				Method:  http.MethodGet,
				Path:    "/user/plans",
				Handler: userplans.UserListPlansHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// List user subscriptions
				Method:  http.MethodGet,
				Path:    "/user/subscriptions",
				Handler: usersubscriptions.UserListSubscriptionsHandler(serverCtx),
			},
			{
				// Preview user subscription
				Method:  http.MethodGet,
				Path:    "/user/subscriptions/:id/preview",
				Handler: usersubscriptions.UserSubscriptionPreviewHandler(serverCtx),
			},
			{
				// Update user subscription template
				Method:  http.MethodPost,
				Path:    "/user/subscriptions/:id/template",
				Handler: usersubscriptions.UserUpdateSubscriptionTemplateHandler(serverCtx),
			},
			{
				// Subscription traffic usage
				Method:  http.MethodGet,
				Path:    "/user/subscriptions/:id/traffic",
				Handler: usersubscriptions.UserSubscriptionTrafficHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Root banner message
				Method:  http.MethodGet,
				Path:    "/",
				Handler: shared.RootHandler(serverCtx),
			},
		},
	)
}
